### ISSUE TITLE
Apple Silicon の Mac で GPU を使って Gemma を動かしたい

### ISSUE THREAD

**Issue by gh640** [gh640/google-gemma-samples-ja#1]
MPS (Metal Performance Shaders) を使うとよいようです。

```python
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b")
# GPU を使うために `device_map="auto"`
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b", device_map="auto")

input_text = "Write me a poem about Machine Learning."
# GPU を使うために `to("mps")`
input_ids = tokenizer(input_text, return_tensors="pt").to("mps")

outputs = model.generate(max_length=30, **input_ids)
print(tokenizer.decode(outputs[0]))
```

## 参考

- https://developer.apple.com/metal/pytorch/
- https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/
- https://huggingface.co/docs/accelerate/en/usage_guides/mps
- https://github.com/huggingface/transformers/issues/22122

**Comment by gh640** [comment]
chat template を使うときは `tokenizer.encode(...).to("mps")` でよさそうです。

```python
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "google/gemma-2b-it"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
)

chat = [
    {"role": "user", "content": "Write a hello world program"},
]
prompt = tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)

inputs = tokenizer.encode(prompt, add_special_tokens=False, return_tensors="pt").to("mps")
outputs = model.generate(input_ids=inputs.to(model.device), max_new_tokens=150)

decoded = tokenizer.decode(outputs[0])
print("decoded:\n", decoded)
```

**Comment by gh640** [comment]
合っている確信は無いですが動きました。

**Comment by luillyfe** [comment]
Still having the error (both approaches):

`RuntimeError: User specified an unsupported autocast device_type 'mps'`

**Comment by gh640** [comment]
@luillyfe 

My explanations above omit assumptions such as dependency versions. Please read the prerequisites and instruction in README first:

https://github.com/gh640/google-gemma-samples-ja

If you get the error even if you've done the same things in README, could you share your environment and steps to reproduce the error?
